module.exports = {
  '5.7': {
    QtQuick: '2.7',
    'QtQuick.Controls': '2.0',
    'QtQuick.Controls.Material': '2.0',
    'QtQuick.Controls.Universal': '2.0',
    'QtQuick.Templates': '2.0',
    'Qt.labs.calendar': '1.0',
    'Qt.labs.platform': '1.0',
    'QtQuick.Layouts': '1.0',
  },
  '5.8': {
    QtQuick: '2.8',
    'QtQuick.Controls': '2.1',
    'QtQuick.Controls.Material': '2.1',
    'QtQuick.Controls.Universal': '2.1',
    'QtQuick.Templates': '2.1',
    'Qt.labs.calendar': '1.0',
    'Qt.labs.platform': '1.0',
    'QtQuick.Layouts': '1.0',
  },
  '5.9': {
    QtQuick: '2.9',
    'QtQuick.Controls': '2.2',
    'QtQuick.Controls.Material': '2.2',
    'QtQuick.Controls.Universal': '2.2',
    'QtQuick.Templates': '2.2',
    'Qt.labs.calendar': '1.0',
    'Qt.labs.platform': '1.0',
    'QtQuick.Layouts': '1.1',
  },
  '5.10': {
    QtQuick: '2.1',
    'QtQuick.Controls': '2.3',
    'QtQuick.Controls.Material': '2.3',
    'QtQuick.Controls.Universal': '2.3',
    'QtQuick.Templates': '2.3',
    'Qt.labs.calendar': '1.0',
    'Qt.labs.platform': '1.0',
    'QtQuick.Layouts': '1.3',
  },
};
